/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Categories: () => import('#controllers/categories_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Products: () => import('#controllers/products_controller'),
  Profile: () => import('#controllers/profile_controller'),
  StockMovements: () => import('#controllers/stock_movements_controller'),
  Stocks: () => import('#controllers/stocks_controller'),
  Warehouses: () => import('#controllers/warehouses_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
}
